### ISSUE TITLE
Spout2 Glitches but only on the way into OBS.

### ISSUE THREAD

**Issue by adbakke** [Off-World-Live/obs-spout2-plugin#20]
**Describe the bug**
When using a Spout2 Capture in OBS the input will glitch out, creating undesired patterning in the video output. Current setup outputs from Magic Music Visuals using Spout2. Output was able to be received using Spout2 Receiver from their Spout2-2.007 kit

**To Reproduce**
1. Output Spout2 source
2. Add Spout2 Source in OBS
3. Use any settings
4. See glitch patterning not expected.

**Expected behavior**
Should output smoothly from Spout2 source.

**Logs from OBS:**
[2021-05-07 22-07-07.txt](https://github.com/Off-World-Live/obs-spout2-source-plugin/files/6444992/2021-05-07.22-07-07.txt)

**Screenshots**
In the attached screenshot the right top is OBS output (glitched)
In the top left is window output directly from Magic Music Visuals
In the bottom middle is the Spout Demo receiver receiving from MMV.
![spout-glitch](https://user-images.githubusercontent.com/5157757/117522617-76e10600-af82-11eb-98ea-52453d7d2a15.png)

**About the Software:**
 - OBS Version 26.1.1
 - OBS Spout 2 Source Plugin Version: latest.

**About Your Machine :**
 - OS: Windows 10
 - GPU: AMD Radeon RX 6700 XT
 - Driver Version: 21.5.1, also tried on previous version
 - RAM 16 GB
 - Machine Type Desktop.
  

**Additional context**
Not sure what else there is to say about it. I'm available for any amount of testing or information gathering.

**Comment by campbellwmorgan** [comment]
Thanks for the very detailed report. This is an extremely strange bug that we haven't seen elsewhere.

Firstly, when you say the latest plugin, you mean the latest stable release, not the v. 27_rc3 pre-release?

Secondly, I noticed in your logs that you have quite a few channels on spout. I'm not sure if its related, but I'd be keen to see if this still happens if you're just sending a single stream to spout?

Finally, do you see this on all spout feeds you send to OBS or just the one from Magic Music Visuals?

Thanks so much for your time in helping us get to the bottom of this

**Comment by adbakke** [comment]
I haven't had a chance to test on a fresh OBS install - I'll have to wait to reset everything as I have a stream tomorrow. This is the odd thing, it only happens with MMV and OBS, but MMV to Spout works fine, MMV to TouchDesigner works fine.

I need to do further testing on it, for now I've used the workaround to output Spout from MMV to TouchDesigner and then TouchDesigner Spout to OBS Studio. Since I don't have a TD license it downscales it, but it at least doesn't glitch. I'll do more testing Wednesday and get back with results. I saw a post on OBS Discord about this plugin from creator (you?), may I message on Discord?

**Comment by campbellwmorgan** [comment]
yes no worries - would be great to get to the bottom of it. I'm on the OBS Studio discord, but best place would be our discord (we also do a bunch of Unreal plugins and this OBS plugin is an essential part of the flow).  https://discord.gg/EqR7FYjqPs - there's a channel for the obs plugin you should find

**Comment by leadedge** [comment]
Hi all,

this is indeed a strange one, although there has been several reports of trouble with AMD graphics in the past and it's a known issue. In this case though it's isolated to Magic>OBS. Also I find that I can successfully resolve it with a plugin using Spout 2.007 methods but I don't know why.

The only thing that comes to mind is preventing concurrent access to the DirectX texture by sender and receiver. I don't know whether your mutex would protect against access by another process. You may know more than me about it. From what I have searched it appears that there is a problem with UpdateSubresource if that happens.

There is already a sender named mutex that can be used to avoid it. I can help with incorporating that if you are interested. It doesn't seem to be necessary in the normal course of events. The GL/DX interop lock acts as a barrier if the texture is updated by OpenGL.

I notice that you are using 2.006 for OBS. You should be able to change over just by copying in the updated files. Only a minor adjustment is needed because the Spout class no longer includes the Sender and Receiver wrapper classes. I can help with that too if you get up to it.

I have no idea whether these things would resolve the problem. @adbakke  has offered to test. Meanwhile there is a workaround using a [plugin for Magic](https://github.com/leadedge/MagicSpout) instead of the main output.

**Comment by campbellwmorgan** [comment]
Hi @leadedge! 
Thanks a lot for dropping in here. We are using 2.006 because we tried to upgrade entirely to 2.007x and we ran into a number of problems which we should really have reported to you but we didn't :( It's been a while, but if I recall we had a number of crashes because it could not create the DirectX context. If you did have a chance to try it out, we'd be really happy to help you getting this OBS plugin built if our timezones overlap so you can try it out yourself (getting OBS setup is a bit of a pain!)

**Comment by leadedge** [comment]
I am keen to get to the bottom of the problems you are having with 2.007. If you could email me some of the symptoms it might lead me to where to look. The DirectX code has not changed much.

I tested the OBS plugin and it works fine for me, but I could not succeed in building OBS itself in order to build the plugin. Without a successful build, I hesitate to proceed with a pull request. But the changes I have in mind are minor, so I can insert them into the existing code without building it and send you a copy. 

I think the functions should be available in the 2.006 code. I will check and be in touch.

**Comment by campbellwmorgan** [comment]
@adbakke We've just finally updated to the latest version of Spout and, I think, possibly fixed some memory issues. I was wondering if you'd mind giving this a go? It's the last one in the releases section.

**Comment by adbakke** [comment]
> @adbakke We've just finally updated to the latest version of Spout and, I think, possibly fixed some memory issues. I was wondering if you'd mind giving this a go? It's the last one in the releases section.

I will give this a shot in the next couple days. Thanks for the update. 

I also have a new GPU to put in soon - so I will test before switching.

**Comment by adbakke** [comment]
I gave this a shot tonight and wasn't able to replicate my earlier issues. I will further test to the best of my ability before swapping out and then of course test extensively with new GPU - Nvidia 3060Ti 🙌

Though I've been using Leadedge magic output for a while and so I have found an easy workaround with that and everything has been pretty smooth since giving that a go in mid-June.

**Comment by campbellwmorgan** [comment]
That's great news! We've had a lot of users with no problem on NVidia cards so if you don't mind I may close this issue for now!

Also nice one getting your hands on a 3060ti!!
