### ISSUE TITLE
A way to install plugin without installer.

### ISSUE THREAD

**Issue by RonYanDaik** [Off-World-Live/obs-spout2-plugin#27]
I've downloaded installer .exe and I'm getting "NSIS Error - error launching installer"

**Describe the solution you'd like**
Can you provide a way and files to install it without installer .exe? 

Also i guess it should be possible install it into Streamlabs OBS since its based on OBS?

**Comment by campbellwmorgan** [comment]
Hi, which release have you downloaded the installer for? 
Please could you try re-downloading the installer because that error you have is usually because the installer file itself has been corrupted.

What version of windows are you on and do you have any antivirus software running?

In terms of streamlabs, no i'm afraid it doesn't work with streamlabs because streamlabs is built upon the underlying obs C api `libobs`, not the full graphical OBS that our plugin is built with. We have been in touch with streamlabs to see if they would consider incorporating our plugin but have not heard back from them.

**Comment by RonYanDaik** [comment]
> which release
latest.

> try re-downloading 
tried several times.

> version of windows
win10. Antivirus disabled.

**Comment by campbellwmorgan** [comment]
Perhaps you could try https://nishantrana.me/2018/12/17/fixed-nsis-error-error-launching-installer-in-windows-10/

This is a strange error because we haven't had any reports of this happening before. Do you have any non-windows antivirus / security programs running that might interfere with downloaded files? What browser did you use to download the executable?

**Comment by RonYanDaik** [comment]
I've downloaded it with another browser. A way to install it by copying dlls still would be nice.

**Comment by 1ucay** [comment]
I have same problem, cannot install anyway. I have portable OBS, Win10m, disabled Defender = no luck.
Can you please attach DLL file without installer?
Thank you.
